# Write your MySQL query statement below\
WITH MAXIS AS (
    SELECT MAX(id) AS IAMMAX FROM Seat 
),TABLE2 AS (
    SELECT id AS CURRENTINDEX , student FROM Seat
)
SELECT  CURRENTINDEX AS id ,
    CASE
        WHEN ((SELECT IAMMAX FROM MAXIS)%2 !=0 ) AND CURRENTINDEX = (SELECT IAMMAX FROM MAXIS) THEN (SELECT student FROM Seat WHERE id =(CURRENTINDEX) )
        WHEN (CURRENTINDEX%2!=0) THEN (SELECT student FROM Seat WHERE id =(CURRENTINDEX+1) )
        ELSE (SELECT student FROM Seat WHERE id =(CURRENTINDEX-1) )
    END  AS student 
    FROM TABLE2 