WITH TABLE1 AS (
    SELECT salary , DENSE_RANK() OVER (ORDER BY salary DESC) AS IMP FROM  Employee
)

SELECT 
    CASE
        WHEN EXISTS(SELECT 1 FROM TABLE1 WHERE IMP = 2) THEN (SELECT salary FROM TABLE1 WHERE IMP=2 LIMIT 1)
        ELSE NULL
    END AS SecondHighestSalary 